---
- id: swag
  name: swag
  description: Cconverts Go annotations to Swagger Documentation
  language: golang
  entry: swag
  always_run: true
  pass_filenames: false
  args: ["init", "--parseDependency"]
