---
- id: swag
  name: swag
  description: Cconverts Go annotations to Swagger Documentation
  language: golang
  entry: swag
  always_run: true
  args: ["init", "--parseDependency", "--parseInternal"]
  pass_filenames: false
